### ISSUE TITLE
Any version of express dependencies ?

### ISSUE THREAD

**Issue by MrFreezeex** [peerigon/socket.io-session-middleware#1]
Could you please add dependencies notes for express version in the readme...
Is this work proprerly with express 4.x ? I can't test by myself now...

**Comment by meaku** [comment]
It works with express 4.x. I'm testing some versions and add some notes about versions to the readme.

**Comment by jhnns** [comment]
Should it be mentioned under `peerDependencies`?

**Comment by meaku** [comment]
Nope. It does not depend on express and can be used with connect, express or plain http.
